### PR TITLE
Add Jupyter support

### PR DESCRIPTION
**Pull request by devjit**
Support for Jupyter (IPython Notebook) on Chrome. Tested on Mac OS X Yosemite. Will continue to do some more testing but wanted feedback from you if there were any design changes.

FYI - this is my first time contributing to another git project - let me know if I break any protocols or other things I should do :-).
-Dev

### CODE REVIEW

**Comment by randy3k** [comment]
It looks interesting. I will test it tomorrow.

**Comment by randy3k** [comment]
It seems that backslashes are not probably escaped. 

Btw, I was trying similar things for `rstudio` on Chrome. But I couldn't figure out what javascript I should run, any thoughts?

**Comment by devjit** [comment]
The backslash thing should be fixed now - thanks for catching that!
Not sure about rstudio - the Jupyter Javascript API is actually not documented (and not intended for the public so not necessarily stable), but I ended up just exploring it in the Chrome Developer Tools Console.   Once I found the module 'IPython' it was pretty straightforward from there. You could also do things to hack the DOM - but it will be likely much more prone to issues.

Anything else you'd like to include in the PR?

**Comment by devjit** [comment]
Reverted that last commit if you want to merge without it - we can move to the tiered preference style in the future...

**Comment by randy3k** [comment]
merged. I tweaked the applescript and javascript code a little bit.

1. It always execute code on the active tab to avoid confusion.

1. it pastes code on the current cell instead.

**Comment by devjit** [comment]
Yeah - that's not a great implementation for our use case since it will
reexecute the previous code every time. It will also silently fail if you
happen to have changed tabs.

In any case - thanks for merging and for building this! I'll keep working
on my fork and let you know if I have any more ideas on how to improve.
-Dev

**Comment by devjit** [comment]
Ah - I see you're inserting a new cell afterwards and selecting that? so -
this overwrites the current cell - not clear why you'd want that as the
default behavior....



On Sat, Nov 14, 2015 at 9:30 AM, Devjit Chakravarti <dchakravarti@lyft.com>
wrote:

> Yeah - that's not a great implementation for our use case since it will
> reexecute the previous code every time. It will also silently fail if you
> happen to have changed tabs.
>
> In any case - thanks for merging and for building this! I'll keep working
> on my fork and let you know if I have any more ideas on how to improve.
> -Dev
>
> On Sat, Nov 14, 2015 at 8:08 AM Randy Lai <notifications@github.com>
> wrote:
>
>> merged. I tweaked the applescript and javascript code a little bit.
>>
>>    1.
>>
>>    It always execute code on the active tab to avoid confusion.
>>    2.
>>
>>    it pastes code on the current cell instead.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/randy3k/SendTextPlus/pull/14#issuecomment-156714365>.
>>
>


-- 
*Devjit Chakravarti*
Data Scientist
310.944.0464 <+13109440464>
[image: Lyft] <http://www.lyft.com/>

**Comment by randy3k** [comment]
The reason is to simulate the <kbd>CMD</kbd>+<kbd>Enter</kbd> behavior.

**Pull request merged**
